VeganCounter.UI/Controllers/Api/VegansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using AutoMapper;
using VeganCounter.BLL.Dtos;
using VeganCounter.BLL.Services;

namespace VeganCounter.UI.Controllers.Api
{
    public class VegansController : ApiController
    {
        private VeganManager _vm;

        public VegansController()
        {
            _vm = new VeganManager();
        }
        // GET /api/vegans
        public IHttpActionResult GetVegans()
        {
            var veganDtos = _vm.EagerGetAll();

            return Ok(veganDtos);
        }



        // GET /api/vegans/1

        public IHttpActionResult GetVegan(int id)
        {
            var veganDto = _vm.Get(id);
            if (veganDto == null)
                return NotFound();
            return Ok(veganDto);
        }

        // POST /api/vegans
        [HttpPost]
        public IHttpActionResult CreateVegan(VeganDto veganDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            
            if (_vm.Add(veganDto))
            {
                veganDto.Id = veganDto.Id;

                return Created(new Uri(Request.RequestUri + "/" + veganDto.Id), veganDto);
            }
            return BadRequest();

        }


        // PUT /api/vegans/1
        [HttpPut]
        public IHttpActionResult UpdateVegan(int id, VeganDto veganDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var veganInDb = _vm.Get(id);

            if (veganInDb == null)
                return NotFound();


            var updatedVeganDto = Mapper.Map(veganDto, veganInDb);

            if (_vm.Update(id, updatedVeganDto))
            {
                return Ok();
            }
            return NotFound();
        }

        //DELETE /api/vegans/1
        [HttpDelete]
        public IHttpActionResult DeleteVegan(int id)
        {
            var veganInDb = _vm.Get(id);

            if (veganInDb == null)
                return NotFound();

            if (_vm.Remove(id))
            {
                return Ok();
            }
            return NotFound();

        }
    }
}

VeganCounter.UI/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - VeganCounter</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("VeganCounter", "Index", "Vegans", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("New Vegan", "New", "Vegans", null, new { @class = "btn btn-primary" })</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - VeganCounter</p>
        </footer>
    </div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>